name: gedi_subset
channels:
  - conda-forge
  - defaults
dependencies:
  - backoff
  - black
  - botocore-stubs
  - contextily
  - ipykernel
  - isort
  - moto
  - mypy
  - mypy-boto3-s3
  - pre-commit
  - pytest
  - types-cachetools
  - types-requests
